name = "wcag-inspector-api"
main = "dist/index.js"
compatibility_date = "2024-04-15"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir="dist/public"

[vars]
ANALYSIS_FETCH_TIMEOUT_MS = "10000"